name: PHPCS

on:
  workflow_call:

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install PHP and dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Set up Composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer

      - name: Prepare tools folder and composer.json
        run: |
          mkdir -p tools
          if [ ! -f tools/composer.json ]; then
            echo '{
              "require-dev": {
                "squizlabs/php_codesniffer": "^3.12",
                "dealerdirect/phpcodesniffer-composer-installer": "*",
                "wp-coding-standards/wpcs": "^3.1"
              }
            }' > tools/composer.json
          fi

      - name: Install PHPCS and WordPress standards
        run: |
          composer config --no-plugins --working-dir=tools allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer install --working-dir=tools --prefer-dist --no-progress --no-interaction

      - name: Run PHPCS
        run: |
          export PATH="$PWD/tools/vendor/bin:$PATH"
          phpcs -n --warning-severity=0 .
