name: Merge Free Version into PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PRO Version (Private)
        uses: actions/checkout@v4
        with:
          repository: ZIORWebDev/easy-dragdrop-file-uploader-pro
          fetch-depth: 0  # Fetch full history

      - name: Pull Latest Updates from PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          # Configure authentication for pushing later
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/easy-dragdrop-file-uploader-pro.git
          
          # Fetch all branches and checkout develop
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/develop; then
            git checkout develop
            git pull origin develop
          else
            git checkout -b develop
            git push origin develop
          fi

      - name: Add Free Version as Remote
        run: |
          git remote add free https://github.com/ZIORWebDev/easy-dragdrop-file-uploader.git || echo "Remote already exists"
          git fetch free main

      - name: Merge Free Version into PRO
        run: |
          # Set Git user identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Merge Free repo into PRO repo, keeping PRO's custom changes
          git merge free/main --allow-unrelated-histories -X theirs || (
            git reset --hard free/main
            git commit -m "Merged updates from Free Version"
          )

          # Restore PRO-specific files
          git checkout develop -- .gitignore README.md composer.json easy-dragdrop-file-uploader.php package.json readme.txt webpack.config.js || true

          # Ensure changes are staged and committed
          git diff --quiet || git commit -m "Synced Free Version updates into PRO"

      - name: Push Merged Changes
        run: |
          git push origin develop
