name: Merge Free Version into PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone the PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          # Clone the PRO repository
          git clone https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/filepond-wp-integration-pro.git pro-repo
          cd pro-repo

          # Fetch all history for proper merging
          git fetch --unshallow || echo "Already unshallowed"
          git fetch origin develop || echo "No remote develop branch found"

          # Checkout develop branch or create it if it doesn't exist
          if git show-ref --verify --quiet refs/remotes/origin/develop; then
            git checkout develop
          else
            git checkout -b develop
            git push origin develop
          fi

          # Merge the latest changes from filepond-wp-integration/main
          git remote add free https://github.com/ZIORWebDev/filepond-wp-integration.git || echo "Remote already exists"
          git fetch free main
