name: Merge Free Version into PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PRO Repository (Private)
        uses: actions/checkout@v4
        with:
          repository: ZIORWebDev/filepond-wp-integration-pro
          fetch-depth: 0  # Fetch full history

      - name: Add Free Version as Remote
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          git remote add free https://github.com/ZIORWebDev/filepond-wp-integration.git || echo "Remote already exists"
          git fetch free main

          # Ensure we are on the develop branch
          git checkout develop || git checkout -b develop

          # Merge Free's main branch into develop with "theirs" strategy (use Free's copy for conflicts)
          git merge --strategy=recursive --strategy-option=theirs free/main || echo "No merge conflicts"

          # Reset unwanted files to keep PRO's versions
          git checkout HEAD -- yarn.lock readme.txt package.json composer.json composer.lock .gitignore .yarn README.md .github

          # Configure Git identity
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit and push changes
          git add .
          git commit -m "Merged filepond-wp-integration/main into develop, preserving PRO-specific files" || echo "No changes to commit"
          git push origin develop
