name: Clone the PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone the PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          git clone --depth 1 https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/filepond-wp-integration-pro.git pro-repo
          cd pro-repo

          # Check if the develop branch exists remotely and has commits
          if git ls-remote --heads origin develop | grep develop; then
            git fetch origin develop
            if git rev-parse --verify origin/develop >/dev/null 2>&1; then
              git checkout -t origin/develop
              git pull origin develop --rebase
            else
              git checkout -b develop
              git push origin develop
            fi
          else
            # If develop branch is empty, create it and push an initial commit
            git checkout -b develop
            touch .placeholder
            git add .placeholder
            git commit -m "Initial commit to develop branch"
            git push origin develop
          fi
          
          # Sync files while excluding unwanted ones
          rsync -av --delete --exclude=".git/" \
                  --exclude="/filepond-wp-integration.php" \
                  --exclude="/webpack.config.js" \
                  --exclude="/package.json" \
                  --exclude="/composer.json" \
                  --exclude="/composer.lock" \
                  --exclude="/.gitignore" \
                  --exclude="/README.md" \
                  --exclude="/.yarn/" \
                  --exclude="/.github/workflows/" \
                  --exclude="/readme.txt" \
                  --exclude="/yarn.lock" \
                  --exclude="/pro-repo/" \
                  --exclude="/index.php" \
                  ../ .

          # Configure Git and commit changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from filepond-wp-integration: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Push changes, retry if necessary
          git push origin develop || (git pull origin develop --rebase && git push origin develop)
