name: Clone the PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4

      - name: Clone the PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          git clone --depth 1 https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/filepond-wp-integration-pro.git pro-repo
          cd pro-repo
          
          # Check if 'develop' branch exists, create it if missing
          if git show-ref --verify --quiet refs/heads/develop; then
            git checkout develop
          else
            git checkout -b develop
            git push origin develop
          fi
          
          # Sync files while excluding unwanted ones
          rsync -av --exclude=".git/" \
                  --exclude="filepond-wp-integration.php" \
                  --exclude="webpack.config.js" \
                  --exclude="package.json" \
                  --exclude="composer.json" \
                  --exclude="composer.lock" \
                  --exclude=".gitignore" \
                  --exclude="README.md" \
                  --exclude=".yarn/" \
                  --exclude=".github/workflows/" \
                  ../filepond-wp-integration/ ./

          # Configure Git and commit changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from filepond-wp-integration: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin develop
