name: Merge Free Version into PRO Repository

on:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4
        with:
          repository: ZIORWebDev/easy-file-uploader
          fetch-depth: 0

      - name: Clone and Merge into PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          echo "GH_TOKEN is set to: ${{ secrets.PRO_REPO_PAT }}"  # Optional debug, remove in production

          # Clone the PRO repository
          git clone https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/easy-file-uploader-pro.git pro-repo
          cd pro-repo
          
          # Fetch all branches to ensure develop exists
          git fetch origin
          if git show-ref --verify --quiet refs/remotes/origin/develop; then
            git checkout develop
          else
            git checkout -b develop
            git push origin develop
          fi
          
          # Add Free repo as remote and fetch its main branch
          git remote add free https://github.com/ZIORWebDev/easy-file-uploader.git || echo "Remote already exists"
          git fetch free main
          
          # Set Git user identity to avoid commit errors
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Merge Free repo into PRO repo while always preferring Free's changes
          git merge free/main --allow-unrelated-histories --strategy-option=theirs || (
            git checkout --theirs .
            git add .
            git commit -m "Merged updates from easy-file-uploader/main into develop"
          )
          
          # Reset unwanted files before pushing
          git checkout HEAD~1 -- .github languages .gitignore README.md composer.json easy-file-uploader.php package.json readme.txt webpack.config.js || true

          # Ensure changes are staged and committed
          git add .
          git commit --amend --no-edit || echo "No changes to amend"
          
          # Push the merged changes
          git push origin develop
