name: Sync to PRO Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4

      - name: Clone the PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          git clone --depth 1 https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/filepond-wp-integration-pro.git pro-repo
          cd pro-repo
          git checkout develop
          rsync -av --exclude=".git/" ../ ./
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Sync from filepond-wp-integration: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin develop
