name: Clone the PRO Repository

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Free Version (Public)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Clone the PRO Repository
        env:
          GH_TOKEN: ${{ secrets.PRO_REPO_PAT }}
        run: |
          git clone --depth 1 https://x-access-token:${GH_TOKEN}@github.com/ZIORWebDev/filepond-wp-integration-pro.git pro-repo
          cd pro-repo

          # Fetch the latest develop branch if it exists
          git fetch origin develop || echo "No remote develop branch found"

          # Ensure we have the latest develop branch
          if git show-ref --verify --quiet refs/remotes/origin/develop; then
            git checkout develop
            git pull --rebase origin develop
          else
            git checkout -b develop
            git push origin develop
          fi
          
          # Sync files while excluding unwanted ones
          rsync -av --delete --exclude=".git/" \
                  --exclude="/filepond-wp-integration.php" \
                  --exclude="/webpack.config.js" \
                  --exclude="/package.json" \
                  --exclude="/composer.json" \
                  --exclude="/composer.lock" \
                  --exclude="/.gitignore" \
                  --exclude="/README.md" \
                  --exclude="/.yarn/" \
                  --exclude="/.github/workflows/" \
                  --exclude="/readme.txt" \
                  --exclude="/yarn.lock" \
                  --exclude="/pro-repo/" \
                  --exclude="/index.php" \
                  ../ .

          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Commit changes
          git add .
          git commit -m "Sync from filepond-wp-integration: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Force push to ensure sync
          git push --force-with-lease origin develop
